module hamiltonian

  use declarations
  use basis
  use v2body
  use v3body_no2b_bin
  use Tcm_2body
  use fwigxjpf
  implicit none   

contains
    ! Here would go the subroutines and functions for Hamiltonian construction

subroutine initialize_hamiltonian


    ! initialization of WIGXJPF library
    CALL fwig_table_init(2*100,9)
    CALL fwig_temp_init(2*100)
    n_sp_levels_calc = dim_HO(Nmax1)
    call kinetic_energy
    call interaction

    ! Further Hamiltonian initialization routines would go here 
return
end subroutine initialize_hamiltonian

subroutine kinetic_energy

    integer :: id,j,k

    id = n_sp_levels_calc

    allocate(T1b_p(id,id),T1b_n(id,id))
    T1b_p=0.d0
    T1b_n=0.d0

    do j=1,id
        T1b_p(j,j) = 0.5d0*hbar_omega*(dble(lev_p(j)%Nosc)+1.5d0)
        do k=1,id
            if(lev_p(j)%l == lev_p(k)%l) then
                if(lev_p(j)%j2 == lev_p(k)%j2) then
                    if(lev_p(j)%nr == lev_p(k)%nr+1) T1b_p(j,k) = 0.5d0*hbar_omega*dsqrt(dble(lev_p(j)%nr)*(dble(lev_p(j)%nr+lev_p(j)%l)+0.5d0))
                    if(lev_p(j)%nr+1 == lev_p(k)%nr) T1b_p(j,k) = 0.5d0*hbar_omega*dsqrt(dble(lev_p(k)%nr)*(dble(lev_p(k)%nr+lev_p(k)%l)+0.5d0))
                endif
            endif
        enddo
    enddo


!    one-body center-of-mass correction to the kinetic energy
    do j=1,id
        do k=1,id
            T1b_p(j,k)=T1b_p(j,k)*(1.d0-1.d0/dfloat(mass_number))
        enddo
    enddo

    T1b_n = T1b_p

    return

end subroutine kinetic_energy
! -------------------------------------------------------------------------
subroutine interaction

    integer :: i,j,k,l,JJ,id
    integer :: jmax_ij_min,jmax_ij_max
    integer :: icm_2b
    real(kind=8) :: factab,factcd

    allocate(Vpp(n_sp_levels,n_sp_levels,n_sp_levels,n_sp_levels,0:j2_lev_max))
    allocate(Vnn(n_sp_levels,n_sp_levels,n_sp_levels,n_sp_levels,0:j2_lev_max))
    allocate(Vpn(n_sp_levels,n_sp_levels,n_sp_levels,n_sp_levels,0:j2_lev_max))

    call read_2b_bin(Nmax1_2N_file,Nmax12_2N_file,hbar_omega,dfloat(mass_number),Nmax1,Nmax12)


!    Two-body center-of-mass Hamiltonian correction
    icm_2b=1

    if (icm_2b /= 0) then

    write(*,*)'Calculation of 2-body part of CM Hamiltonian'
    factab=1.d0
    factcd=1.d0
    id=n_sp_levels_calc

!!$OMP PARALLEL DEFAULT(SHARED) 
!!$OMP& PRIVATE(i,j,k,l,JJ,factab,factcd,jmax_ij_min,jmax_ij_max)
!!$OMP DO
    do i=1,id
!    write(*,*)'i=',i,id
         do j=1,id
          factab=1.d0
          if(i.eq.j) factab=dsqrt(2.d0)
          jmax_ij_min=iabs((lev_n(i)%j2-lev_n(j)%j2)/2)
          jmax_ij_max=(lev_n(i)%j2+lev_n(j)%j2)/2
          do k=1,id
           do l=1,id
            
            if ((100000*i+j) >= (100000*k+l)) then
             
            factcd=1.d0
            if(k.eq.l) factcd=dsqrt(2.d0)

!             do JJ=0,jmax
             do  JJ=jmax_ij_min,jmax_ij_max

!       2-body part of CM Hamiltonian
!         if (dabs(Vpn(i,j,k,l,JJ)) > 1.d-10) then 
          Vpn(i,j,k,l,JJ)=Vpn(i,j,k,l,JJ)+hbar_omega/dfloat(mass_number)*T_nn(i,j,k,l,JJ)
        
          Vpn(k,l,i,j,JJ) = Vpn(i,j,k,l,JJ)

!         endif 
!         if (dabs(Vpp(i,j,k,l,JJ)) > 1.d-10) then 
          Vpp(i,j,k,l,JJ)=Vpp(i,j,k,l,JJ)+hbar_omega/dfloat(mass_number)*T_nn_asym(i,j,k,l,JJ)*factab*factcd  
!         endif

          Vpp(k,l,i,j,JJ) = Vpp(i,j,k,l,JJ)

!         if (dabs(Vnn(i,j,k,l,JJ)) > 1.d-10) then
          Vnn(i,j,k,l,JJ)=Vnn(i,j,k,l,JJ)+hbar_omega/dfloat(mass_number)*T_nn_asym(i,j,k,l,JJ)*factab*factcd

          Vnn(k,l,i,j,JJ) = Vnn(i,j,k,l,JJ)
!          endif

            enddo

            endif 
           enddo
          enddo
         enddo
        enddo 
!!$OMP END DO
!!$OMP END PARALLEL

    endif

!      Compressing of 2-body  elements
    call Compress_2b(Nmax1_2N_file,Nmax12_2N_file,Nmax1,Nmax12,n_sp_levels,j2_lev_max)     

!    Reading of 3-body NO2B elements from binary file generated by NuHamil code
    call read_3b_no2b_bin(Nmax1_3N_file,Nmax12_3N_file,Nmax123_3N_file,Nmax1,Nmax12,Nmax123)



return
end subroutine interaction


end module hamiltonian